unbind C-b
set-option -g prefix C-s
bind C-s send-prefix
bind-key e send-prefix

# The idea here is to switch panes using Alt + vim dirs
bind -n M-l next-window
bind -n M-h previous-window


unbind l # last-window
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

set -g mouse on
set -g status-position bottom
set -g status-bg colour234
set -g status-fg colour137
set -g status-left '' 
set -g status-right '#[fg=colour233,bg=colour241,bold] %d/%m #[fg=colour233,bg=colour245,bold] %H:%M:%S '
set -g status-right-length 50
set -g status-left-length 20
setw -g mode-keys vi

setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour50]#F '

setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

set-option -g history-limit 10000

# Start indexing at 1 instead of 0
set -g base-index 1          # Start window numbering at 1
setw -g pane-base-index 1     # Start pane numbering at 1
set -g renumber-windows on   # Renumber after closing

# tmux yank to clipboard. Should just work with terminals that support OSC52. Good for remote ssh
set -s set-clipboard on
set-option -g allow-passthrough on


# Copy command 
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "tmux-copy.sh"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "tmux-copy.sh"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "tmux-copy.sh"
